---
title: The SRL Documentation
description: Documentation of SRL
url: "https://dadepu.github.io/srscs-doc/"

remote_theme: alexander-heimbuch/millidocs

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

---